title: Play Pickups Blog
email: contact@playpickups.app
description: >- 
  Write an awesome description for your new site here.
baseurl: "/blog"
url: "https://kaxevgg.github.io"
permalink: /:categories/:title/

# Important: Specify layouts directory
layouts_dir: _layouts

# Theme and plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag